// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiQbc84uCEvYn9cT5pgxW0ngRnHiajbmI',
    appId: '1:262949963987:web:164749589ad7e69147ec26',
    messagingSenderId: '262949963987',
    projectId: 'task-manager-66ab5',
    authDomain: 'task-manager-66ab5.firebaseapp.com',
    storageBucket: 'task-manager-66ab5.firebasestorage.app',
    measurementId: 'G-93JV4Z157M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIdQMMAH1xCtzS5MK9x0FBZfRe578VQOc',
    appId: '1:262949963987:android:f2a15af9c8cfec7847ec26',
    messagingSenderId: '262949963987',
    projectId: 'task-manager-66ab5',
    storageBucket: 'task-manager-66ab5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArWudL7B0GISTD_DHlM0MEpKCg6acibA0',
    appId: '1:262949963987:ios:cb6f29985fc17af747ec26',
    messagingSenderId: '262949963987',
    projectId: 'task-manager-66ab5',
    storageBucket: 'task-manager-66ab5.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArWudL7B0GISTD_DHlM0MEpKCg6acibA0',
    appId: '1:262949963987:ios:cb6f29985fc17af747ec26',
    messagingSenderId: '262949963987',
    projectId: 'task-manager-66ab5',
    storageBucket: 'task-manager-66ab5.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiQbc84uCEvYn9cT5pgxW0ngRnHiajbmI',
    appId: '1:262949963987:web:a6209137804c280a47ec26',
    messagingSenderId: '262949963987',
    projectId: 'task-manager-66ab5',
    authDomain: 'task-manager-66ab5.firebaseapp.com',
    storageBucket: 'task-manager-66ab5.firebasestorage.app',
    measurementId: 'G-NZNFSQWPG4',
  );
}
